### ISSUE TITLE
Close not unlocking on page complete

### ISSUE THREAD

**Issue by KayConceicao** [cgkineo/adapt-pageNav#51]
### Subject of the issue/enhancement/features
Describe your issue here.
The close button is not unlocking when the page is complete although the next button locking is working fine.

### Your environment
* version (AT/Framework) 
AAT version: 0.10.5 | Framework version: 5.25.0
* which browser and its version
Chrome - latest version

### Steps to reproduce
Tell us how to reproduce this issue.
Required page with PageNav at the bottom of the page (page is not added to plp). Close is set to unlock once page is complete. Click through components close button doesn't unlock unless you go to menu or previous page and return to page with close button.

### Expected behaviour
Tell us what should happen
Close button should unlock after page complete as per next button.

### Actual behaviour
Tell us what happens instead
Close button does not unlock even after the page is complete.

**Comment by oliverfoster** [comment]
It sounds very much like something else is happening which is causing the page to not complete.

It's the same bit of code which manages both buttons.

https://github.com/cgkineo/adapt-pageNav/blob/0eb5467f5d8dfaa72af94e1f0549e02dbb2a0fdc/js/view.js#L32
https://github.com/cgkineo/adapt-pageNav/blob/0eb5467f5d8dfaa72af94e1f0549e02dbb2a0fdc/js/model.js#L91

Any console logs?

**Comment by oliverfoster** [comment]
As the close button doesn't have an `_id` attribute it fails on this line:
https://github.com/cgkineo/adapt-pageNav/blob/0eb5467f5d8dfaa72af94e1f0549e02dbb2a0fdc/js/view.js#L80

Which prevents the button from rerendering on page:_isComplete change.

**Comment by oliverfoster** [comment]
Bug is probably fixed in upcoming pr https://github.com/cgkineo/adapt-pageNav/pull/49
But that pr is not 100% backward compatible.
So as not to impede the progress of that pr, I'm not going to do a bug fix release for this right now. The only solution for a running AAT is to upload a custom version of this plugin with that bug fixed.

**Comment by tomallpress** [comment]
I'm still seeing this behaviour in a course I'm building in the AAT, using v2.4.0

**Comment by StuartNicholls** [comment]
@oliverfoster sorry, not got to this yet

**Comment by oliverfoster** [comment]
v2.4.0 was the last version before the aforementioned pr, I would expect it to have the bug.
pr which made v3.0.0 https://github.com/cgkineo/adapt-pageNav/pull/49

Have tested with latest v3.1.3, cannot replicate.
![pageNav close button](https://github.com/cgkineo/adapt-pageNav/assets/7974663/1a7c485b-0939-4962-9cc1-d6e855c9b5f7)
